#!/usr/bin/env bash
# Bump the build number in bootrom.asm
source paths.inc || exit 1

src="$path_src/bootrom.asm"
ident='\(^\t.DB\s"\)\([[:digit:]]\+\)\(".*IdentifierCommentForBuildNumAutoBump.*\)'

if [ ! -e "$src" ]
then
    echo "$src: File not found. Have you set the correct path?" >&2
    exit 1
fi

set -e

build_old=$(grep IdentifierCommentForBuildNumAutoBump "$src" \
            | grep \.DB \
            | awk -F \" '{print $2}')

let build_new="$build_old + 1"

echo "Old build: $build_old"
echo "New build: $build_new"

sed -i.bak -e "s/${ident}/\1${build_new}\3/" "$src"
