#!/usr/bin/env bash
source paths.inc || exit 1

(
    cd $path_src
    rm *.lst *.sfc *.sym *.tmp *.usage *.o > /dev/null 2>&1
    cd $path_out
    rm Valid.ext *.log *.usage > /dev/null 2>&1
)

exit 0
